language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
    - develop

env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - PROJECT="Project/LLRegex.xcodeproj"
        - IOS_FRAMEWORK_SCHEME="LLRegex iOS"
        - MACOS_FRAMEWORK_SCHEME="LLRegex macOS"
        - TVOS_FRAMEWORK_SCHEME="LLRegex tvOS"
        - WATCHOS_FRAMEWORK_SCHEME="LLRegex watchOS"
        - HAS_TEST="YES"
    matrix:
    
        - DESTINATION="OS=2.0,name=Apple Watch - 42mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME"  HAS_TEST="NO"
        
        - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"    SCHEME="$IOS_FRAMEWORK_SCHEME"     
        - DESTINATION="OS=9.0,name=iPhone 6"            SCHEME="$IOS_FRAMEWORK_SCHEME"
        - DESTINATION="OS=8.1,name=iPhone 4S"           SCHEME="$IOS_FRAMEWORK_SCHEME"
    
        - DESTINATION="OS=10.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"
        - DESTINATION="OS=9.0,name=Apple TV 1080p"      SCHEME="$TVOS_FRAMEWORK_SCHEME"
        
        - DESTINATION="arch=x86_64"                     SCHEME="$MACOS_FRAMEWORK_SCHEME"
script:
    - xcodebuild -version
    - xcodebuild -showsdks
    
    # DEBUG
    - if [ $HAS_TEST == "YES" ]; then
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
      else
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      fi
      
    # RELEASE
    - if [ $HAS_TEST == "YES" ]; then
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
      else
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
      fi